### PR TITLE
Email renewals

### PR DESCRIPTION
**Pull request by hyanwong**
Fixes some bugs in renewals

### CODE REVIEW

**Comment by hyanwong** [comment]
@lentinj - do you know if all the changes in the PR have now been incorporated into `main`?

**Comment by lentinj** [comment]
Their equivalents on main are https://github.com/OneZoom/OZtree/commit/fb96f14ff9802aaa25827f0aeb7e0180a450bb38  & https://github.com/OneZoom/OZtree/commit/5fd240dfe0eb92a944caedb847cd21a81f2ff181

**Comment by hyanwong** [comment]
Great, so I can close this then? Thanks

**Comment by lentinj** [comment]
Yeah, there's nothing left to do here.

**Pull request closed without merging**
