### PR TITLE
NPM upgrade incl. webpack 5

### PR DESCRIPTION
**Pull request by lentinj**
Upgrade everything in NPM land, in particular webpack 5

Needs way more testing, and solving sass deprecations, but basically works.

I'll try with a new onezoom container when I get a chance to rebuild.

### CODE REVIEW

**Comment by lentinj** [comment]
Also worth noting that a handful of packages only support NPM 18. I've changed the readme in the above, but we should probably be sure that there isn't anything left on NPM 16 before merging.

**Comment by hyanwong** [comment]
Great, thanks for this @lentinj : great to keep on top of it all.

**Comment by lentinj** [comment]
@hyanwong Everything here seems to work fine in a fresh Ubuntu 22.04 container, so this could be merged I think.

The Node 18 requirement should be fine with the new servers, but might be worth checking it builds fine on beta first before merging.

**Comment by hyanwong** [comment]
Great. I will check it builds on beta an then merge. Thanks a lot @lentinj !

**Pull request merged**
