### PR TITLE
Update preferred_python3 to 3.10. Python 3.7 is no longer supported.

### PR DESCRIPTION
**Pull request by wolfmanstout**
If memory serves, this is also the Python version in the latest Docker image of alpine-compass-python-perl-node. We could also use a later version; I was just being conservative.

### CODE REVIEW

**Comment by davidebbo** [comment]
I believe the plan is actually to move to 3.11. See #672. @hyanwong may be in the process of making this change?

Personally, I've been on 3.10, which is what comes with Ubuntu 22.04.

**Comment by hyanwong** [comment]
It seems like the new OneZoom server will be running 3.10 in a few days, so I think that should be our target.

**Comment by wolfmanstout** [comment]
Ok, I applied the change both here and to the Dev Container pull request. Note that this new version of Python also requires a more recent version of web2py in order to use the web2py.py server script (or else you get an error from a deprecated threading library call), so I also updated that in my Dev Container, which means it no longer aligns with the version configured in the main Dockerfile. Should we update that too?

**Comment by wolfmanstout** [comment]
Send a pull request to update the Dockerfile to align: https://github.com/OneZoom/OZtree-docker/pull/3

**Comment by lentinj** [comment]
I'll be merging https://github.com/OneZoom/OZtree/pull/711 soon, which does this along with a bunch of other stuff, so will close this and merge that if that's okay.

@hyanwong I'd merge https://github.com/OneZoom/OZtree-docker/pull/3 but I'm not allowed to.

**Pull request closed without merging**
