### PR TITLE
Replace compass with grunt-sass+dart-sass (now called "sass" in npm)

### PR DESCRIPTION
**Pull request by hyanwong**
It's annoying to require ruby just for compass, which is outdated anyway. This PR uses only nodes stuff, so we can get rid of ruby. Does this work for you @lentinj ?

### CODE REVIEW

**Comment by lentinj** [comment]
The extra commits are what I need to get things going, I'm not sure if the plugin upgrades were truly necessary anyway?

**Comment by hyanwong** [comment]
Ha - I was just trying to sort this, thanks! I wondered whether to update to webpack 5 too?

**Comment by lentinj** [comment]
Can always try and see what the fallout is? I'd say it's worth merging this first, then moving on to trying webpack 5.

And yes, less dependencies is always a good thing.

**Comment by hyanwong** [comment]
I just tried with web pack 5 and there are a few deprecation errors, but it seems to work OK. I wonder if the packed files are smaller - will have a look. Meanwhile I agree about merging this, thanks.

**Pull request merged**
