### PR TITLE
Onezoom js hashtag

### PR DESCRIPTION
**Pull request by kz12**
OneZoom core package is named OZEntry.js regardless of its content change. It might cause user not being able to fetch the latest OZEntry script due to browser cache or server file cache. 

These two commits adds a hash number in filename whenever OZEntry content changes. It also dynamically generates a html file which includes a script tag referring to the new OZEntry file. References to OZEntry.js in html files, mainly in layout.html and treetour.html, are replaced by references to the dynamic generated html file. This guarantees that the html files would always refer to the latest OZEntry filename.

Now the uglify and compress process is handled by webpack in its production mode. Grunt cannot do it because it does not know the exact name of the newly generated OZEntry file. In order to handle it, webpack and some babel dependencies has been updated to the latest version. Hence, please remove node_modules folder and run 'npm install' after you fetch these commits.

### CODE REVIEW

**Comment by hyanwong** [comment]
That seems sensible.

While you are thinking about webpack, we also want to be able to use the search API on other webpages (e.g. the OneZoom frontpage, `/default/index.html`. Can we easily abstract out the API search functionality into a separate smaller compressed library, or perhaps simply use the existing one but without defining a canvas?

**Comment by hyanwong** [comment]
Also, if you are looking at OZentry, would it be easy to implement https://github.com/OneZoom/OZtree/issues/180 ?

**Comment by kz12** [comment]
Sorry for the late response.

You can do both. You can either add another entry in webpack, or you can export the functions you want in OZEntry. For example, you can add the following in OZEntry.js:

```
//export OZEntry.default
export default setup;

//export OZEntry.api_manager
export {api_manager};
```

**Comment by hyanwong** [comment]
This is now incorporated into the new homepage stuff, see a22f8513e7e82360779d1adc0a67bcdca28f233d, and will therefore eventually make it onto the main site, so I'm closing the PR.

**Pull request closed without merging**
