### PR TITLE
Update page length column number in SQL csv

### PR DESCRIPTION
**Pull request by davidebbo**
The code was based on an earlier version of the dump

### CODE REVIEW

**Comment by hyanwong** [comment]
Well spotted. I haven't checked this but it doesn't surprise me, and I'm happy to merge. I wonder if there is a way to pull out the column ID from the file without reading the entire thing into SQL, which would probably be prohibitive. Is there and SQL header sniffer library somewhere?

**Comment by davidebbo** [comment]
It wouldn't be too hard to write a bit of parsing logic to get the index of `page_namespace`, `page_title` and `page_len` within the `CREATE TABLE` statement:

```sql
CREATE TABLE `page` (
  `page_id` int(8) unsigned NOT NULL AUTO_INCREMENT,
  `page_namespace` int(11) NOT NULL DEFAULT 0,
  `page_title` varbinary(255) NOT NULL DEFAULT '',
  `page_is_redirect` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `page_is_new` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `page_random` double unsigned NOT NULL DEFAULT 0,
  `page_touched` binary(14) NOT NULL,
  `page_links_updated` varbinary(14) DEFAULT NULL,
  `page_latest` int(8) unsigned NOT NULL DEFAULT 0,
  `page_len` int(8) unsigned NOT NULL DEFAULT 0,
  `page_content_model` varbinary(32) DEFAULT NULL,
  `page_lang` varbinary(35) DEFAULT NULL,
  PRIMARY KEY (`page_id`),
  UNIQUE KEY `page_name_title` (`page_namespace`,`page_title`),
  KEY `page_random` (`page_random`),
  KEY `page_len` (`page_len`),
  KEY `page_redirect_namespace_len` (`page_is_redirect`,`page_namespace`,`page_len`)
) ENGINE=InnoDB AUTO_INCREMENT=72635263 DEFAULT CHARSET=binary ROW_FORMAT=COMPRESSED;
```

It probably doesn't change too often, so not a high pri. Next time it breaks, I'll fix it the right way :)

**Comment by hyanwong** [comment]
Yeah, we could sniff it ourselves, but that seems a bit hacky.

**Comment by hyanwong** [comment]
E.g. https://github.com/andialbrecht/sqlparse

**Comment by davidebbo** [comment]
Created an issue to track this possible improvement.

**Pull request merged**
