### PR TITLE
Add recent places to search dropdown

### LINKED ISSUE #878: Fiddly to add the current node to common ancestors
Sometimes I find I've done a search (and maybe it's taken me a while to find precisely the node I was looking for) and then I decide that I want to do a common ancestors view of this and something else. At the moment, I have to manually search for this node again in the common ancestors view, which feels like an extra step.

### PR DESCRIPTION
**Pull request by jaredkhan**
Adds a 'recent places' section to the search dropdown.
Only captures items that you have clicked in the search dropdown (not things that you have arrived at via URL or panned to in the viewer)
Has a 'Clear recents' button.
Still works with click and drag to common ancestor etc (didn't know this feature was there!)
I've added it to the homepage too.
Length is limited to 5 items.
Visiting the same item from a search result twice will reposition it in the list rather than duplicating it.
Items are stored in localStorage so that they survive a refresh.

Fixes #878

### CODE REVIEW

**Comment by davidebbo** [comment]
Works great!

A few comments, all minor:
- Maybe bump the limit to 8 or 10. Though in my tree, I don't have any 'Popular Places' to compete with. Maybe it can take that into account somehow. i.e. SomeMax - NumOfPopPlaces.
- Maybe show the taxon name in addition to the vernacular, which is what happens in the regular search result?
- Maybe add to the list when you actually click on a node and pop up the inline wiki page? I'm not sold on this one, as this could end up spamming the list.

> Still works with click and drag to common ancestor etc (didn't know this feature was there!)

Wow, didn't know that either!

**Comment by jaredkhan** [comment]
Thanks for your comments @davidebbo!
I've bumped the max up to 8.
It now pushes to the recents list when clicking on a node too. See what you think, I think it's fairly sensible but I suppose it depends how many nodes you click on.
It now includes the latin name in the recents listings.

**Comment by hyanwong** [comment]
Great. I'll just merge this then, and we can tweak later if necessary. Thanks so much @jaredkhan

**Comment by davidebbo** [comment]
@jaredkhan one possible concern: once we turn that on in the main tree as well, are https://www.onezoom.org/life/ and https://www.onezoom.org/extinct/life/ going to end up sharing the same list? Or can it be smart enough to differentiate them in how they're stored (since they are kept across sessions)?

**Comment by jaredkhan** [comment]
Yeah good point, it certainly would share the same list at the moment.

**Comment by davidebbo** [comment]
I think this is worth addressing. Presumably, it's as simple as using a key modifier in `localStorage.setItem()`, e.g. `'recent_places_extinct'` (maybe based on the path segment before the `/life` segment if any.

**Pull request merged**
