### PR TITLE
Remove treebuild

### PR DESCRIPTION
**Pull request by hyanwong**
And update dependencies, python version, etc

### CODE REVIEW

**Comment by davidebbo** [comment]
@hyanwong looking at the changes, it does not seem to match the "Remove treebuild" PR name.

**Comment by lentinj** [comment]
@davidebbo I think all of this happened in https://github.com/OneZoom/OZtree/pull/765, bar the python version change that became 3.10 anyway.

**Comment by hyanwong** [comment]
Yeah, I started out on it, but didn't finish, and everything had moved on by then. So the "real removal" is/was in #816

**Comment by davidebbo** [comment]
Got it, thanks.

**Pull request closed without merging**
